-- TimescaleDB Schema for Trading Engine
-- Run this script to initialize the database

-- Enable TimescaleDB extension
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ============================================================================
-- TICKS TABLE
-- Raw tick data from market feeds
-- ============================================================================
CREATE TABLE IF NOT EXISTS ticks (
    time        TIMESTAMPTZ NOT NULL,
    symbol      TEXT NOT NULL,
    price       NUMERIC(12,4) NOT NULL,
    volume      NUMERIC(12,2),
    bid         NUMERIC(12,4),
    ask         NUMERIC(12,4)
);

-- Create hypertable for time-series optimization
SELECT create_hypertable('ticks', 'time', if_not_exists => TRUE);

-- Index for symbol lookups
CREATE INDEX IF NOT EXISTS idx_ticks_symbol_time ON ticks (symbol, time DESC);

-- ============================================================================
-- CANDLES TABLE
-- OHLCV candle data for multiple timeframes
-- ============================================================================
CREATE TABLE IF NOT EXISTS candles (
    time        TIMESTAMPTZ NOT NULL,
    symbol      TEXT NOT NULL,
    timeframe   TEXT NOT NULL,  -- '1m', '5m', '15m', '1h', '1d', etc.
    open        NUMERIC(12,4) NOT NULL,
    high        NUMERIC(12,4) NOT NULL,
    low         NUMERIC(12,4) NOT NULL,
    close       NUMERIC(12,4) NOT NULL,
    volume      NUMERIC(12,2) DEFAULT 0,
    tick_count  INTEGER DEFAULT 0,
    UNIQUE(symbol, timeframe, time)
);

SELECT create_hypertable('candles', 'time', if_not_exists => TRUE);

-- Composite index for efficient queries
CREATE INDEX IF NOT EXISTS idx_candles_symbol_tf_time
    ON candles (symbol, timeframe, time DESC);

-- ============================================================================
-- MARKET STRUCTURE TABLE
-- Detected market structure events (swing points, FVGs, order blocks, etc.)
-- ============================================================================
CREATE TABLE IF NOT EXISTS market_structure (
    time        TIMESTAMPTZ NOT NULL,
    symbol      TEXT NOT NULL,
    timeframe   TEXT NOT NULL,
    type        TEXT NOT NULL,  -- 'swing_point', 'fvg', 'order_block', 'bos', etc.
    data        JSONB NOT NULL  -- Type-specific payload
);

SELECT create_hypertable('market_structure', 'time', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_market_structure_symbol_type
    ON market_structure (symbol, type, time DESC);

-- ============================================================================
-- INDICATORS TABLE
-- Computed indicator values
-- ============================================================================
CREATE TABLE IF NOT EXISTS indicators (
    time          TIMESTAMPTZ NOT NULL,
    symbol        TEXT NOT NULL,
    indicator_id  TEXT NOT NULL,
    timeframe     TEXT NOT NULL,
    value         JSONB NOT NULL
);

SELECT create_hypertable('indicators', 'time', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_indicators_symbol_id
    ON indicators (symbol, indicator_id, time DESC);

-- Add unique constraint to indicators table for upserts
CREATE UNIQUE INDEX IF NOT EXISTS idx_indicators_unique
    ON indicators (symbol, indicator_id, timeframe, time);

-- ============================================================================
-- STRATEGY SIGNALS TABLE
-- Trading signals generated by strategies
-- ============================================================================
CREATE TABLE IF NOT EXISTS strategy_signals (
    time          TIMESTAMPTZ NOT NULL,
    symbol        TEXT NOT NULL,
    strategy_id   TEXT NOT NULL,
    signal_type   TEXT NOT NULL,  -- 'entry', 'exit', 'stop', 'target'
    data          JSONB NOT NULL
);

SELECT create_hypertable('strategy_signals', 'time', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_signals_symbol_strategy
    ON strategy_signals (symbol, strategy_id, time DESC);

-- ============================================================================
-- RETENTION POLICIES (Optional)
-- Automatically drop old data to manage storage
-- ============================================================================

-- Keep ticks for 7 days (high-frequency data)
-- SELECT add_retention_policy('ticks', INTERVAL '7 days', if_not_exists => TRUE);

-- Keep candles for 2 years
-- SELECT add_retention_policy('candles', INTERVAL '2 years', if_not_exists => TRUE);

-- Keep market structure for 1 year
-- SELECT add_retention_policy('market_structure', INTERVAL '1 year', if_not_exists => TRUE);

-- Keep indicators for 1 year
-- SELECT add_retention_policy('indicators', INTERVAL '1 year', if_not_exists => TRUE);

-- Keep signals for 2 years
-- SELECT add_retention_policy('strategy_signals', INTERVAL '2 years', if_not_exists => TRUE);

-- ============================================================================
-- COMPRESSION POLICIES (Optional)
-- Compress old data to save storage
-- ============================================================================

-- Compress ticks older than 1 day
-- ALTER TABLE ticks SET (timescaledb.compress);
-- SELECT add_compression_policy('ticks', INTERVAL '1 day', if_not_exists => TRUE);

-- Compress candles older than 7 days
-- ALTER TABLE candles SET (timescaledb.compress);
-- SELECT add_compression_policy('candles', INTERVAL '7 days', if_not_exists => TRUE);

-- ============================================================================
-- CONTINUOUS AGGREGATES (Optional)
-- Pre-computed rollups for faster queries
-- ============================================================================

-- Example: Hourly candle summary from 1m candles
-- CREATE MATERIALIZED VIEW candles_1h
-- WITH (timescaledb.continuous) AS
-- SELECT
--     time_bucket('1 hour', time) AS time,
--     symbol,
--     '1h' as timeframe,
--     first(open, time) as open,
--     max(high) as high,
--     min(low) as low,
--     last(close, time) as close,
--     sum(volume) as volume,
--     sum(tick_count) as tick_count
-- FROM candles
-- WHERE timeframe = '1m'
-- GROUP BY time_bucket('1 hour', time), symbol;

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Get latest candle for a symbol/timeframe
CREATE OR REPLACE FUNCTION get_latest_candle(
    p_symbol TEXT,
    p_timeframe TEXT
) RETURNS TABLE (
    time TIMESTAMPTZ,
    open NUMERIC,
    high NUMERIC,
    low NUMERIC,
    close NUMERIC,
    volume NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT c.time, c.open, c.high, c.low, c.close, c.volume
    FROM candles c
    WHERE c.symbol = p_symbol AND c.timeframe = p_timeframe
    ORDER BY c.time DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;

-- Get candles in time range
CREATE OR REPLACE FUNCTION get_candles(
    p_symbol TEXT,
    p_timeframe TEXT,
    p_start TIMESTAMPTZ,
    p_end TIMESTAMPTZ DEFAULT NOW()
) RETURNS TABLE (
    time TIMESTAMPTZ,
    open NUMERIC,
    high NUMERIC,
    low NUMERIC,
    close NUMERIC,
    volume NUMERIC
) AS $$
BEGIN
    RETURN QUERY
    SELECT c.time, c.open, c.high, c.low, c.close, c.volume
    FROM candles c
    WHERE c.symbol = p_symbol
      AND c.timeframe = p_timeframe
      AND c.time >= p_start
      AND c.time <= p_end
    ORDER BY c.time ASC;
END;
$$ LANGUAGE plpgsql;
